/* YIHOT: public-source-only information triage. Every rendered item keeps a citation. */
const ALLOWED_SOURCE_IDS = new Set(["reliefweb", "un-news", "un-official"]);
const ALLOWED_SOURCE_HOSTS = new Set(["reliefweb.int", "news.un.org", "www.un.org", "un.org"]);
// 公开部署后端（腾讯云 CloudBase 云函数）地址。留空时走本地同源 /api/*，
// 并依次回退到 /api/feeds 与 data/feeds.json（GitHub Pages 烘焙数据）。
const YIHOT_API_BASE = "";
const DEMO_ITEMS = [
  { id: "demo-1", topic: "灾害救援", title: "沿海强降雨预警：多个社区开放临时安置点", summary: "公开通告提到志愿者登记、饮用水和儿童用品需求，公益团队可先核验本地联系人与服务时间。", source: "地方应急公开通告（演示）", sourceType: "政府公开页面", url: "https://www.gov.cn/", published: "2026-08-23T08:30:00+08:00", action: true, score: 86, heat: 94, reports: 4, recommendation: "先核对地区、更新时间和安置点联系方式，再决定是否转入组织流程。" },
  { id: "demo-2", topic: "资金", title: "社区小额公益项目开放新一轮申报", summary: "申报窗口、预算上限和材料清单已公布，适合加入组织内部提醒队列。", source: "公益项目公开页面（演示）", sourceType: "公开申报", url: "https://www.gov.cn/", published: "2026-08-22T16:00:00+08:00", action: true, score: 79, heat: 82, reports: 3, recommendation: "打开原文确认截止时间和适用地区，避免把公开征集误作获资承诺。" },
  { id: "demo-3", topic: "政策", title: "无障碍服务采购指引更新，新增验收条款", summary: "条款涉及服务对象反馈和验收记录，建议由项目负责人确认适用地区。", source: "公共政策来源（演示）", sourceType: "政策公开页", url: "https://www.un.org/zh/", published: "2026-08-22T11:20:00+08:00", action: false, score: 72, heat: 68, reports: 2, recommendation: "记录版本号与生效日期，再和当前项目合同逐项对照。" },
  { id: "demo-4", topic: "志愿者", title: "周末流动服务站招募双语志愿者", summary: "岗位说明、培训时间和报名入口均来自公开页面，报名之前请核对组织身份。", source: "志愿服务公开公告（演示）", sourceType: "组织公告", url: "https://www.unv.org/", published: "2026-08-21T09:10:00+08:00", action: true, score: 74, heat: 73, reports: 2, recommendation: "先验证报名域名、服务地点与联系人，不要在雷达中提交个人证件信息。" },
  { id: "demo-5", topic: "资金", title: "儿童阅读资助计划发布结项报告", summary: "报告包含项目目标、覆盖人数和公开联系方式，可作为合作尽调的起点而非结论。", source: "基金会公开报告（演示）", sourceType: "公开报告", url: "https://www.unicef.org/", published: "2026-08-20T15:40:00+08:00", action: false, score: 63, heat: 54, reports: 1, recommendation: "把报告中的数字与原始附件、审计说明和更新时间一起留档。" },
  { id: "demo-6", topic: "公共服务", title: "联合国发布社区韧性工具包更新版", summary: "工具包整理了社区评估、风险沟通和志愿者协作的公开模板，适合项目团队参考。", source: "联合国官方更新（演示）", sourceType: "官方 RSS", url: "https://www.un.org/en/", published: "2026-08-23T01:20:00+08:00", action: true, score: 81, heat: 77, reports: 3, recommendation: "下载前先确认版本与许可范围，引用时保留原文标题和链接。" },
  { id: "demo-7", topic: "政策", title: "公开咨询：基层公共服务数字化标准征求意见", summary: "征求意见页面列出反馈渠道与截止日期，公益组织可从服务对象角度整理意见。", source: "公共政策来源（演示）", sourceType: "政府公开页面", url: "https://www.gov.cn/", published: "2026-08-19T12:05:00+08:00", action: true, score: 58, heat: 46, reports: 1, recommendation: "确认反馈渠道是否仍开放，提交内容前由组织内部完成脱敏。" }
];
const VIEW_META = {
  featured: { crumb: "精选", title: "精选", subtitle: "今天值得公益团队先打开原文、再决定是否行动的公开变化。", kicker: "公开来源情报", panel: "今日精选", panelKicker: "今日精选" },
  all: { crumb: "全部动态", title: "全部动态", subtitle: "按时间查看 allowlist 公开源的最新更新，每条信息都保留引用。", kicker: "公开更新", panel: "公开信息流", panelKicker: "全部更新" },
  hot: { crumb: "热点榜", title: "热点榜", subtitle: "过去 48 小时正在升温的公共议题，先看趋势，再回到原文复核。", kicker: "热点雷达", panel: "48 小时热榜", panelKicker: "当前热点" },
  daily: { crumb: "公益日报", title: "公益日报", subtitle: "每天 08:00，把公开变化压缩成一份可引用的组织晨读。", kicker: "公益日报", panel: "公益日报", panelKicker: "每日简报" },
  topics: { crumb: "主题", title: "主题", subtitle: "按灾害、政策、资金、志愿者和公共服务整理阅读路径。", kicker: "主题", panel: "主题目录", panelKicker: "按议题浏览" },
  starred: { crumb: "收藏", title: "收藏", subtitle: "只在本地保存你想稍后回到原文复核的公开更新。", kicker: "收藏", panel: "已收藏", panelKicker: "稍后复核" },
  queue: { crumb: "复核队列", title: "复核队列", subtitle: "把需要打开原文、核对时间与地区的条目放在组织内部工作台。", kicker: "工作队列", panel: "组织复核队列", panelKicker: "内部复核" },
  sources: { crumb: "来源目录", title: "来源目录", subtitle: "当前版本只访问配置文件中的 HTTPS RSS/Atom 公开源。", kicker: "来源", panel: "公开来源", panelKicker: "公开源目录" }
};
const TOPIC_DESCRIPTIONS = { 灾害救援: "预警、安置、物资和灾害响应的公开更新。", 政策: "政策、标准、征求意见和公共治理页面。", 资金: "公开申报、资助计划、结项与资金说明。", 志愿者: "志愿岗位、培训、服务站和招募公告。", 公共服务: "面向社区的服务工具、指南和资源。" };
const REFRESH_INTERVAL_MS = 60 * 1000;
const STREAM_URL = YIHOT_API_BASE ? "" : "/api/stream";
const MAX_LIVE_ITEMS = 240;
const state = { items: [...DEMO_ITEMS], filter: "all", sourceFilter: "all", query: "", range: "48h", actionOnly: false, currentView: "featured", dailyDate: null, queue: loadStoredCompat("yihot-queue", "civic-radar-queue", []), starred: loadStoredCompat("yihot-starred", "civic-radar-starred", []), live: false, hasLiveData: false, autoRefresh: loadStoredCompat("yihot-auto-refresh", "civic-radar-auto-refresh", true) !== false, refreshIntervalMs: REFRESH_INTERVAL_MS, timer: null, countdownTimer: null, stream: null, streamState: "idle", streamRetryTimer: null, streamRetryDelayMs: 5000, pendingRefresh: false, nextRefreshAt: null, lastSyncAt: null, lastGoodAt: null, sourceStatuses: [], sourceErrorCount: 0, pendingNewIds: [], refreshInFlight: false, lastError: "" };
const $ = (id) => document.getElementById(id);
function loadStored(key, fallback) { try { const value = JSON.parse(localStorage.getItem(key) || "null"); if (fallback === null) return value; return Array.isArray(value) ? value : fallback; } catch { return fallback; } }
function loadStoredCompat(key, legacyKey, fallback) { try { const current = localStorage.getItem(key); if (current !== null) return JSON.parse(current); const legacy = localStorage.getItem(legacyKey); return legacy === null ? fallback : JSON.parse(legacy); } catch { return fallback; } }
function saveStored(key, value) { try { localStorage.setItem(key, JSON.stringify(value)); } catch { /* file:// and restricted storage are valid demo modes */ } }
const translateCache = loadStoredCompat("yihot-zh-cache-v1", "civic-zh-cache-v1", {}) || {};
let translateInFlight = false;
const CJK_RE = /[\u3400-\u9fff\uf900-\ufaff]/;
const needsTranslation = (text) => Boolean(text) && !CJK_RE.test(text) && /[A-Za-z]/.test(text);
async function translateVisibleItems() {
  if (translateInFlight) return;
  const targets = state.items.filter((item) => needsTranslation(item.title) || needsTranslation(item.summary));
  if (!targets.length) return;
  const applyCached = (item) => {
    if (needsTranslation(item.title) && translateCache[item.title]) { item.titleOriginal = item.titleOriginal || item.title; item.title = translateCache[item.title]; }
    if (needsTranslation(item.summary) && translateCache[item.summary]) { item.summaryOriginal = item.summaryOriginal || item.summary; item.summary = translateCache[item.summary]; }
  };
  const pendingTexts = [];
  for (const item of targets) {
    if (needsTranslation(item.title) && !translateCache[item.title]) pendingTexts.push(item.title);
    if (needsTranslation(item.summary) && !translateCache[item.summary]) pendingTexts.push(item.summary);
    applyCached(item);
  }
  const unique = [...new Set(pendingTexts)].slice(0, 60);
  if (!unique.length) { render({ preserveViewport: true }); return; }
  translateInFlight = true;
  try {
    const response = await fetch(`${YIHOT_API_BASE}/api/translate`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ texts: unique }) });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const payload = await response.json();
    const translations = Array.isArray(payload?.translations) ? payload.translations : [];
    unique.forEach((text, index) => { const zh = typeof translations[index] === "string" ? translations[index].trim() : ""; translateCache[text] = zh || text; });
    const keys = Object.keys(translateCache);
    if (keys.length > 800) { for (const key of keys.slice(0, keys.length - 800)) delete translateCache[key]; }
    saveStored("yihot-zh-cache-v1", translateCache);
    for (const item of targets) applyCached(item);
    render({ preserveViewport: true });
  } catch { /* translate service unavailable: keep original English text */ } finally { translateInFlight = false; }
}
const applyFeedPayloadBase = applyFeedPayload;
applyFeedPayload = function (payload, origin = "poll") { const result = applyFeedPayloadBase(payload, origin); void translateVisibleItems(); return result; };
async function fetchFeedPayload() {
  const endpoints = YIHOT_API_BASE ? [`${YIHOT_API_BASE}/api/feeds`, "/api/feeds", "data/feeds.json"] : ["/api/feeds", "data/feeds.json"];
  let lastError = null;
  for (const url of endpoints) {
    try { const response = await fetch(url, { cache: "no-store" }); if (!response.ok) throw new Error(`HTTP ${response.status}`); return await response.json(); } catch (error) { lastError = error; }
  }
  throw lastError || new Error("no feed endpoint available");
}
function escapeHtml(value) { return String(value ?? "").replace(/[&<>"']/g, (c) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "\"":"&quot;", "'":"&#39;" }[c])); }
function safeHref(value, fallback = "https://www.gov.cn/") { try { const url = new URL(String(value || fallback), window.location.href); return ["https:", "http:"].includes(url.protocol) ? url.href : fallback; } catch { return fallback; } }
function sourceHost(value) { try { return new URL(value).hostname.toLowerCase(); } catch { return ""; } }
function stableHash(value) { let hash = 2166136261; for (const char of String(value || "")) { hash ^= char.charCodeAt(0); hash = Math.imul(hash, 16777619); } return (hash >>> 0).toString(36); }
function formatRelative(value) { const date = new Date(value); if (Number.isNaN(date.valueOf())) return "--"; const seconds = Math.max(0, Math.round((Date.now() - date.valueOf()) / 1000)); if (seconds < 60) return "刚刚"; if (seconds < 3600) return `${Math.floor(seconds / 60)} 分钟前`; if (seconds < 86400) return `${Math.floor(seconds / 3600)} 小时前`; return `${Math.floor(seconds / 86400)} 天前`; }
function formatCountdown(value) { if (!value) return "--:--"; const timestamp = typeof value === "number" ? value : Date.parse(value); if (!Number.isFinite(timestamp)) return "--:--"; const seconds = Math.max(0, Math.ceil((timestamp - Date.now()) / 1000)); if (seconds > 3599) return `${Math.floor(seconds / 3600)}h`; return `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; }
function formatInterval(value) { const seconds = Math.max(1, Math.round(Number(value || REFRESH_INTERVAL_MS) / 1000)); return seconds >= 60 ? `每 ${Math.round(seconds / 60)} 分钟` : `每 ${seconds} 秒`; }
function formatDate(value, options = {}) { const date = new Date(value); if (Number.isNaN(date.valueOf())) return "时间未知"; return date.toLocaleString("zh-CN", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", ...options }); }
function dayKey(value) { const date = new Date(value); return Number.isNaN(date.valueOf()) ? "unknown" : date.toLocaleDateString("zh-CN", { year: "numeric", month: "2-digit", day: "2-digit" }); }
function dayLabel(value) { const date = new Date(value); if (Number.isNaN(date.valueOf())) return "日期未知"; return date.toLocaleDateString("zh-CN", { month: "long", day: "numeric" }); }
function weekday(value) { const date = new Date(value); return Number.isNaN(date.valueOf()) ? "" : date.toLocaleDateString("zh-CN", { weekday: "short" }); }
function topicClass(topic) { return topic === "资金" ? "orange" : topic === "灾害救援" ? "red" : topic === "公共服务" ? "blue" : ""; }
function isQueued(id) { return state.queue.some((item) => item.id === id); }
function isStarred(id) { return state.starred.includes(id); }
function scoreFor(item) { if (Number.isFinite(Number(item.score))) return Math.max(1, Math.min(99, Number(item.score))); const age = Math.max(0, (Date.now() - new Date(item.published).getTime()) / 36e5); const keyword = /预警|开放|招募|申报|更新|工具包|征求/.test(`${item.title} ${item.summary}`) ? 12 : 0; return Math.round(Math.max(35, 78 - age * 1.3 + keyword)); }
function enrich(item, source) { const title = item.title || "无标题公开更新"; const summary = (item.summary || "来自公开来源的更新，请打开原文核验。").replace(/<[^>]+>/g, "").slice(0, 300); const topic = item.topic || inferTopic(`${title} ${summary}`); const published = item.published || new Date().toISOString(); return { id: String(item.id || `${source?.id || "source"}-${published}-${title.slice(0, 18)}`), sourceId: item.sourceId || source?.id || "", topic, title, summary, source: item.source || source?.name || "公开来源", sourceType: item.sourceType || "RSS/Atom", url: safeHref(item.url, source?.url || "https://www.gov.cn/"), published, action: Boolean(item.action ?? topic !== "政策"), score: scoreFor({ ...item, published }), heat: Number(item.heat) || Math.max(25, Math.min(98, scoreFor({ ...item, published }) + 5)), reports: Number(item.reports) || 1, recommendation: item.recommendation || "打开原文核对时间、地区和上下文，再由工作人员决定是否行动。", firstSeenAt: item.firstSeenAt || Date.now(), updatedAt: item.updatedAt || Date.now() }; }
function inferTopic(text) { if (/灾|洪水|地震|救援|应急|避难|预警/.test(text)) return "灾害救援"; if (/募|资助|基金|捐赠|申报|预算/.test(text)) return "资金"; if (/志愿|招募|服务站|培训/.test(text)) return "志愿者"; if (/社区|工具包|服务|资源/.test(text)) return "公共服务"; return "政策"; }
function sourceMatches(item) { if (state.sourceFilter === "all") return true; const type = `${item.sourceType} ${item.source}`; if (state.sourceFilter === "official") return /官方|政府|政策/.test(type); if (state.sourceFilter === "rss") return /RSS|Atom/i.test(type); if (state.sourceFilter === "organization") return /组织|公告|公开报告|公开申报/.test(type); return true; }
function filteredItems() { const now = Date.now(); const maxAge = state.range === "48h" ? 48 : state.range === "7d" ? 168 : Infinity; return state.items.filter((item) => { const age = (now - new Date(item.published).getTime()) / 36e5; const topicOk = state.filter === "all" || item.topic === state.filter; const rangeOk = !Number.isFinite(maxAge) || age <= maxAge || age < 0; const actionOk = !state.actionOnly || item.action; const hay = `${item.title} ${item.summary} ${item.source} ${item.topic}`.toLowerCase(); return topicOk && sourceMatches(item) && rangeOk && actionOk && (!state.query || hay.includes(state.query.toLowerCase())); }).sort((a, b) => new Date(b.published) - new Date(a.published)); }
function setStatus(text, kind = "demo", detail = "") { const status = $("source-status"); status.textContent = text; const dot = $("sidebar-status-dot"); dot.dataset.state = kind; $("sync-detail").textContent = detail; $("last-sync").textContent = new Date().toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit" }); $("sync-count").textContent = detail || "本地演示数据"; }
function renderCard(item, compact = false) { const queued = isQueued(item.id); const starred = isStarred(item.id); const isNew = state.pendingNewIds.includes(item.id); return `<article class="feed-card${compact ? " compact" : ""}${isNew ? " is-new" : ""}"><div class="feed-top"><span class="topic-tag ${topicClass(item.topic)}">${escapeHtml(item.topic)}</span>${isNew ? `<span class="new-tag">新</span>` : ""}<span class="source-name">${escapeHtml(item.source)}</span><span>·</span><span class="source-type">${escapeHtml(item.sourceType)}</span><span>·</span><time>${formatDate(item.published)}</time><span class="score-badge" title="规则提示分，不代表事实结论"><strong>${item.score}</strong> 编辑提示分</span></div><div class="feed-title-row"><h3><a href="${escapeHtml(safeHref(item.url))}" target="_blank" rel="noopener noreferrer">${escapeHtml(item.title)}</a></h3><button class="star-btn" data-star="${escapeHtml(item.id)}" type="button" aria-label="${starred ? "取消收藏" : "收藏"}" aria-pressed="${starred}">${starred ? "★" : "☆"}</button></div><p class="feed-summary">${escapeHtml(item.summary)}</p>${compact ? "" : `<div class="reason"><strong>推荐理由</strong>${escapeHtml(item.recommendation)}</div>`}<div class="feed-bottom"><a href="${escapeHtml(safeHref(item.url))}" target="_blank" rel="noopener noreferrer">查看原文 ↗</a><div class="card-actions"><span class="muted">${item.reports} 个公开信源</span><button class="queue-btn" data-queue="${escapeHtml(item.id)}" type="button" aria-pressed="${queued}">${queued ? "已在队列" : "加入复核"}</button></div></div></article>`; }
function renderFeed(list = filteredItems(), groupByDay = true) { const feed = $("feed-list"); $("empty-state").hidden = list.length > 0; if (!list.length) { feed.innerHTML = ""; return; } if (!groupByDay) { feed.innerHTML = list.map((item) => renderCard(item)).join(""); return; } const groups = new Map(); list.forEach((item) => { const key = dayKey(item.published); if (!groups.has(key)) groups.set(key, []); groups.get(key).push(item); }); feed.innerHTML = [...groups.values()].map((items) => `<section class="date-group"><div class="date-heading"><strong>${escapeHtml(dayLabel(items[0].published))}</strong><span>${escapeHtml(weekday(items[0].published))} · ${items.length} 条</span></div>${items.map((item) => renderCard(item)).join("")}</section>`).join(""); }
function renderHot(list) { const hot = [...list].sort((a, b) => b.heat - a.heat || new Date(b.published) - new Date(a.published)); $("hot-list").innerHTML = hot.length ? hot.map((item, index) => `<article class="hot-row"><div class="hot-rank">${String(index + 1).padStart(2, "0")}</div><div class="hot-main"><a href="${escapeHtml(safeHref(item.url))}" target="_blank" rel="noopener noreferrer">${escapeHtml(item.title)}</a><div class="hot-meta"><span class="topic-tag ${topicClass(item.topic)}">${escapeHtml(item.topic)}</span><span>${escapeHtml(item.source)}</span><span>·</span><span>${formatDate(item.published)}</span><span>${item.reports} 个信源</span></div></div><div class="hot-side"><div class="heat-value">${item.heat}<small> 热度提示</small></div><span class="heat-side-label">规则估算 · 48h 半衰</span><div class="heat-meter"><i style="width:${Math.max(4, Math.min(100, item.heat))}%"></i></div></div></article>`).join("") : `<div class="empty"><span class="empty-mark">⌁</span><strong>48 小时内暂无热点</strong><span>刷新公开源或放宽筛选条件。</span></div>`; }
  function renderDaily(list) { const groups = new Map(); list.forEach((item) => { const key = dayKey(item.published); if (!groups.has(key)) groups.set(key, []); groups.get(key).push(item); }); const dates = [...groups.entries()].slice(0, 10); if (!dates.length) { $("daily-history-list").innerHTML = ""; $("daily-paper-content").innerHTML = `<div class="empty"><strong>暂无日报素材</strong></div>`; return; } if (!state.dailyDate || !groups.has(state.dailyDate)) state.dailyDate = dates[0][0]; $("daily-history-list").innerHTML = dates.map(([key, items]) => `<button class="history-item ${key === state.dailyDate ? "active" : ""}" data-daily-date="${escapeHtml(key)}" type="button"><strong>${escapeHtml(new Date(items[0].published).toLocaleDateString("zh-CN", { month: "2-digit", day: "2-digit" }))}</strong><span>${escapeHtml(items[0].title)}</span></button>`).join(""); const selected = groups.get(state.dailyDate) || dates[0][1]; const byTopic = new Map(); selected.forEach((item) => { if (!byTopic.has(item.topic)) byTopic.set(item.topic, []); byTopic.get(item.topic).push(item); }); const toc = selected.slice(0, 5).map((item, i) => `<a href="#daily-${escapeHtml(item.id)}"><b>${String(i + 1).padStart(2, "0")}</b><span>${escapeHtml(item.topic)}</span><span>${escapeHtml(item.title)}</span></a>`).join(""); const sections = [...byTopic.entries()].map(([topic, items], index) => `<section class="daily-section" id="daily-${escapeHtml(items[0].id)}"><div class="daily-section-head"><strong>${String(index + 1).padStart(2, "0")}</strong><h4>${escapeHtml(topic)}</h4><small>${items.length} 篇</small></div>${items.slice(0, 3).map((item) => `<div class="daily-story"><a href="${escapeHtml(safeHref(item.url))}" target="_blank" rel="noopener noreferrer">${escapeHtml(item.title)}</a><p>${escapeHtml(item.summary)}</p><small>${escapeHtml(item.source)} · ${formatDate(item.published)} · 原文可追溯</small></div>`).join("")}</section>`).join(""); $("daily-paper-content").innerHTML = `<div class="daily-overline">VOL. ${escapeHtml(state.dailyDate.replaceAll("/", "."))} · YIHOT DAILY</div><h3>公益日报</h3><div class="daily-date">${escapeHtml(new Date(selected[0].published).toLocaleDateString("zh-CN", { year: "numeric", month: "long", day: "numeric", weekday: "long" }))} · 每早八时</div><div class="daily-toc"><div class="daily-toc-title"><span>今日看点</span><span>${selected.length} 篇报道 · 约 ${Math.max(1, Math.ceil(selected.length * 1.2))} 分钟</span></div>${toc}</div>${sections}<p class="muted" style="margin-top:24px">本页为规则整理的阅读提纲。涉及人身、捐赠和安全的内容请回到原文并完成人工复核。</p>`; }
function renderTopics(list) { const groups = new Map(); list.forEach((item) => { if (!groups.has(item.topic)) groups.set(item.topic, []); groups.get(item.topic).push(item); }); const order = ["灾害救援", "政策", "资金", "志愿者", "公共服务"]; $("topics-list").innerHTML = order.filter((topic) => groups.has(topic)).map((topic) => { const items = groups.get(topic); const top = [...items].sort((a, b) => b.heat - a.heat)[0]; return `<article class="topic-card"><span class="topic-tag ${topicClass(topic)}">${escapeHtml(topic)}</span><h4>${items.length} 条公开更新</h4><p>${escapeHtml(TOPIC_DESCRIPTIONS[topic] || "公开来源的主题归类。")}</p><strong>${top.heat}</strong><small>当前最高热度提示 · ${escapeHtml(top.source)}</small></article>`; }).join("") || `<div class="empty"><strong>暂无主题素材</strong></div>`; }
function renderStarred(list) { const starred = list.filter((item) => isStarred(item.id)); $("starred-list").innerHTML = starred.map((item) => renderCard(item)).join(""); $("starred-empty").hidden = starred.length > 0; }
function renderQueue() { const queue = state.queue; $("queue-list").innerHTML = queue.length ? queue.map((item) => `<article class="queue-row"><i></i><div><h4>${escapeHtml(item.title)}</h4><p>${escapeHtml(item.source)} · ${escapeHtml(item.topic)} · ${formatDate(item.published)}</p><small>原文：${escapeHtml(safeHref(item.url))}</small></div><div class="card-actions"><a class="outline-btn" href="${escapeHtml(safeHref(item.url))}" target="_blank" rel="noopener noreferrer">打开原文</a><button class="queue-btn" data-queue="${escapeHtml(item.id)}" type="button" aria-pressed="true">移出队列</button></div></article>`).join("") : `<div class="empty"><span class="empty-mark">✓</span><strong>复核队列为空</strong><span>在条目底部加入需要人工核对的公开更新。</span></div>`; }
function renderSources() { const seen = new Map(); state.items.forEach((item) => { if (!seen.has(item.source)) seen.set(item.source, item); }); $("sources-grid").innerHTML = [...seen.values()].map((item) => `<article class="source-tile"><h4>${escapeHtml(item.source)}</h4><p>${escapeHtml(item.sourceType)} · 仅保留公开引用</p><a href="${escapeHtml(safeHref(item.url))}" target="_blank" rel="noopener noreferrer">访问来源 ↗</a></article>`).join("") || `<div class="empty"><strong>暂无来源</strong></div>`; }
function renderRail() { const top = [...state.items].sort((a, b) => b.heat - a.heat)[0]; $("now-card").innerHTML = top ? `<a class="now-story" href="${escapeHtml(safeHref(top.url))}" target="_blank" rel="noopener noreferrer"><span class="now-score">${top.heat} 热度提示 · ${escapeHtml(top.topic)}</span><div class="now-title">${escapeHtml(top.title)}</div><div class="now-meta">${escapeHtml(top.source)} · ${formatDate(top.published)}</div><div class="heat-meter"><i style="width:${top.heat}%"></i></div></a>` : `<p class="rail-empty">暂无热点素材</p>`; $("rail-queue-list").innerHTML = state.queue.length ? state.queue.slice(0, 3).map((item) => `<div class="rail-queue-item"><i></i><div><p>${escapeHtml(item.title)}</p><small>${escapeHtml(item.topic)} · ${formatDate(item.published)}</small></div></div>`).join("") : `<p class="rail-empty">队列为空。把需要核验的条目加入这里。</p>`; const sourceMap = new Map(); state.items.forEach((item) => { if (!sourceMap.has(item.source)) sourceMap.set(item.source, item); }); $("rail-source-list").innerHTML = [...sourceMap.values()].slice(0, 5).map((item) => `<div class="rail-source"><div><a href="${escapeHtml(safeHref(item.url))}" target="_blank" rel="noopener noreferrer">${escapeHtml(item.source)}</a><small>${escapeHtml(item.sourceType)}</small></div></div>`).join("") || `<p class="rail-empty">暂无来源</p>`; }
function renderSourceHealth() { const sources = state.sourceStatuses; const ok = sources.filter((source) => source.status === "ok").length; const errors = sources.filter((source) => source.status === "error").length; $("source-health-summary").textContent = sources.length ? `${ok}/${sources.length} 正常${errors ? ` · ${errors} 异常` : ""}` : "待同步"; $("source-health-list").innerHTML = sources.length ? sources.map((source) => { const status = source.status === "ok" ? "ok" : source.status === "error" ? "error" : "pending"; const detail = status === "ok" ? (source.fetchedAt ? formatRelative(source.fetchedAt) : "正常") : status === "error" ? "暂不可用" : "等待"; return `<div class="source-health-row"><i class="source-health-dot ${status}"></i><span class="source-health-name" title="${escapeHtml(source.name || source.id)}">${escapeHtml(source.name || source.id || "公开源")}</span><span class="source-health-detail" title="${escapeHtml(source.error || detail)}">${escapeHtml(detail)}</span></div>`; }).join("") : `<p class="rail-empty">点击刷新后显示每个公开源状态。</p>`; }
function renderNewItemsBanner() { const count = state.pendingNewIds.length; const banner = $("new-items-banner"); banner.hidden = count === 0; $("new-items-count").textContent = count; const first = state.items.find((item) => item.id === state.pendingNewIds[0]); $("new-items-detail").textContent = first ? `${first.title}${count > 1 ? ` 等 ${count} 条已加入当前信息流` : "已加入当前信息流"}` : "已加入当前信息流"; }
function renderRealtimeSummary() { const recent = state.lastSyncAt ? `最近更新：${formatRelative(state.lastSyncAt)} · ${state.items.length} 条` : "最近更新：--"; $("recent-update-summary").textContent = recent; const hotCount = state.items.filter((item) => (Date.now() - new Date(item.published).getTime()) <= 48 * 36e5).length; const dailyKey = dayKey(Date.now()); const dailyCount = state.items.filter((item) => dayKey(item.published) === dailyKey).length; $("hot-sync-state").textContent = `热榜：${hotCount} 条 · ${state.lastSyncAt ? formatRelative(state.lastSyncAt) : "待同步"}`; $("daily-sync-state").textContent = `日报：${dailyCount} 篇 · ${state.lastSyncAt ? formatRelative(state.lastSyncAt) : "待同步"}`; }
function renderRealtimeState() { const pulse = $("realtime-pulse"); const mode = $("sync-mode"); const label = $("realtime-label"); const detail = $("realtime-detail"); const status = $("source-status"); const dot = $("sidebar-status-dot"); const syncDot = $("sync-status-dot"); let kind = state.streamState; if (state.refreshInFlight) kind = "syncing"; if (!state.autoRefresh) kind = "paused"; if (kind === "idle") kind = state.hasLiveData ? "polling" : "error"; const copy = { live: ["实时在线", "EventSource 已连接"], polling: ["轮询在线", `${formatInterval(state.refreshIntervalMs)} · 下次 ${formatCountdown(state.nextRefreshAt)}`], connecting: ["正在连接", "尝试实时流，失败将自动轮询"], syncing: ["同步中…", "正在读取已配置的公开源"], paused: ["已暂停自动刷新", "手动点击刷新仍可用"], error: ["暂时离线", state.lastError || "保留最近一次可用数据"], stale: ["连接暂时中断", state.lastError || "保留最近一次可用数据"] }[kind] || ["等待同步", "准备公开源连接"]; pulse.className = `live-pulse ${kind}`; mode.textContent = copy[0]; label.textContent = copy[0]; detail.textContent = copy[1]; status.textContent = state.hasLiveData ? (state.sourceErrorCount ? "部分源在线" : "公开源在线") : (kind === "error" ? "演示数据" : "连接中…"); dot.dataset.state = state.sourceErrorCount ? "error" : state.hasLiveData ? "live" : "demo"; syncDot.dataset.state = state.sourceErrorCount ? "error" : state.hasLiveData ? "live" : "demo"; $("last-sync").textContent = state.lastSyncAt ? new Date(state.lastSyncAt).toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit" }) : "--:--"; $("next-refresh").textContent = state.autoRefresh ? (state.streamState === "live" ? "实时流" : formatCountdown(state.nextRefreshAt)) : "已暂停"; $("auto-refresh-btn").textContent = state.autoRefresh ? "暂停自动刷新" : "恢复自动刷新"; $("auto-refresh-btn").setAttribute("aria-pressed", String(!state.autoRefresh)); $("poll-toggle").checked = state.autoRefresh; $("poll-label").textContent = state.autoRefresh ? `${formatInterval(state.refreshIntervalMs)}自动刷新` : "自动刷新已暂停"; renderRealtimeSummary(); }
function updateCountdown() { renderRealtimeState(); }
function updateCounters() { const list = filteredItems(); const sourceCount = new Set(state.items.map((item) => item.source)).size; const fresh = state.items.filter((item) => (Date.now() - new Date(item.published).getTime()) <= 24 * 36e5).length; $("result-count").textContent = `${list.length} 条`; $("source-count").textContent = sourceCount; $("fresh-count").textContent = fresh; $("review-count").textContent = state.queue.length; $("action-count").textContent = state.items.filter((item) => item.action).length; $("queue-count").textContent = state.queue.length; $("topic-count").textContent = new Set(state.items.map((item) => item.topic)).size; $("nav-featured-count").textContent = Math.min(99, state.items.filter((item) => item.score >= 70).length); $("nav-all-count").textContent = Math.min(99, state.items.length); $("nav-topic-count").textContent = new Set(state.items.map((item) => item.topic)).size; $("nav-starred-count").textContent = state.starred.length; $("nav-queue-count").textContent = state.queue.length; $("nav-source-count").textContent = sourceCount; $("mobile-queue-count").textContent = state.queue.length; $("sync-count").textContent = state.live ? `${state.items.length} 条可引用更新` : "本地演示数据"; renderSourceHealth(); renderNewItemsBanner(); renderRealtimeState(); }
function render(options = {}) { const viewportY = options.preserveViewport ? window.scrollY : null; const list = filteredItems(); updateCounters(); renderRail(); if (state.currentView === "featured") renderFeed(list, true); if (state.currentView === "all") renderFeed(list, false); if (state.currentView === "hot") renderHot(list); if (state.currentView === "daily") renderDaily(list); if (state.currentView === "topics") renderTopics(list); if (state.currentView === "starred") renderStarred(list); if (state.currentView === "queue") renderQueue(); if (state.currentView === "sources") renderSources(); if (viewportY !== null) requestAnimationFrame(() => window.scrollTo({ top: viewportY, behavior: "auto" })); }
function setView(view) { state.currentView = VIEW_META[view] ? view : "featured"; const meta = VIEW_META[state.currentView]; $("crumb-view").textContent = meta.crumb; $("page-kicker").textContent = meta.kicker; $("page-title").textContent = meta.title; $("page-subtitle").textContent = meta.subtitle; $("panel-kicker").textContent = meta.panelKicker; $("panel-title").textContent = meta.panel; document.querySelectorAll(".nav-item, .mobile-nav button").forEach((button) => button.classList.toggle("active", button.dataset.view === state.currentView)); document.querySelectorAll(".view").forEach((viewNode) => { const active = viewNode.id === `${state.currentView}-view`; viewNode.hidden = !active; viewNode.classList.toggle("active-view", active); }); document.querySelector(".sidebar")?.classList.remove("open"); $("menu-toggle").setAttribute("aria-expanded", "false"); render(); }
function sameSourceHost(value, sourceUrl) { try { const url = new URL(value); const host = url.hostname.toLowerCase(); const sourceHostName = sourceHost(sourceUrl); return url.protocol === "https:" && Boolean(host && sourceHostName && (host === sourceHostName || host.endsWith(`.${sourceHostName}`))); } catch { return false; } }
function parseFeedXml(xml, source) { if (!source || !ALLOWED_SOURCE_IDS.has(source.id) || !ALLOWED_SOURCE_HOSTS.has(sourceHost(source.url))) return []; const doc = new DOMParser().parseFromString(xml, "text/xml"); return [...doc.querySelectorAll("item, entry")].slice(0, 30).map((node) => { const text = (selector) => node.querySelector(selector)?.textContent?.trim() || ""; const linkNode = node.querySelector("link"); const candidate = safeHref(linkNode?.getAttribute("href") || linkNode?.textContent?.trim() || source.url, source.url); const url = sameSourceHost(candidate, source.url) ? candidate : safeHref(source.url); const title = text("title") || "无标题公开更新"; const summary = (text("description") || text("summary") || "").replace(/<[^>]+>/g, "").slice(0, 300); const published = text("pubDate") || text("published") || text("updated") || new Date().toISOString(); const rawId = text("guid") || text("id") || url || `${title}|${published}`; const topic = inferTopic(`${title} ${summary}`); return enrich({ id: `${source.id}-${stableHash(rawId)}`, sourceId: source.id, topic, title, summary, source: source.name, sourceType: "RSS/Atom", url, published, action: topic !== "政策", reports: 1 }, source); }); }
function mergeLiveItems(nextItems) { const oldById = new Map(state.items.map((item) => [item.id, item])); const added = []; nextItems.forEach((item) => { const previous = oldById.get(item.id); if (!previous && state.hasLiveData) added.push(item); oldById.set(item.id, { ...(previous || {}), ...item, firstSeenAt: previous?.firstSeenAt || item.firstSeenAt || Date.now(), updatedAt: Date.now() }); }); const merged = [...oldById.values()].filter((item) => item.sourceId || !state.hasLiveData).sort((a, b) => new Date(b.published) - new Date(a.published)).slice(0, MAX_LIVE_ITEMS); const freshById = new Map(merged.map((item) => [item.id, item])); state.queue = state.queue.map((item) => freshById.get(item.id) || item); return { items: merged, added }; }
function applyFeedPayload(payload, origin = "poll") { const sources = Array.isArray(payload?.sources) ? payload.sources : []; const serverInterval = Number(payload?.refreshIntervalMs); if (serverInterval >= 15000) state.refreshIntervalMs = serverInterval; const nextRefresh = payload?.nextRefreshAt ? new Date(payload.nextRefreshAt).getTime() : NaN; if (Number.isFinite(nextRefresh)) state.nextRefreshAt = nextRefresh; const bakedItems = Array.isArray(payload?.items) && payload.items.length ? payload.items : null; const liveItems = bakedItems || sources.filter((source) => ALLOWED_SOURCE_IDS.has(source.id) && (source.status === "ok" || (source.status === "error" && source.stale)) && source.xml).flatMap((source) => parseFeedXml(source.xml, source)); const hadLive = state.hasLiveData; let added = []; if (liveItems.length) { if (hadLive) { const merged = mergeLiveItems(liveItems); state.items = merged.items; added = merged.added; } else { state.items = liveItems.map((item) => enrich(item)); } state.hasLiveData = true; state.live = true; state.lastGoodAt = payload?.lastSuccessAt || payload?.fetchedAt || new Date().toISOString(); state.lastError = ""; if (hadLive && added.length) state.pendingNewIds = [...new Set([...state.pendingNewIds, ...added.map((item) => item.id)])]; } else if (!hadLive) { state.items = DEMO_ITEMS.map((item) => enrich(item)); state.live = false; state.lastError = sources.length ? "远端源暂不可用，保留演示数据" : "未收到公开源数据"; } else { state.live = true; state.lastError = "本次没有可用源，保留最近一次同步"; }
  state.sourceStatuses = sources; state.sourceErrorCount = sources.filter((source) => source.status === "error").length; const syncAt = payload?.fetchedAt || payload?.refreshedAt; if (syncAt && sources.length) state.lastSyncAt = syncAt; state.streamState = origin === "stream" ? "live" : state.streamState === "live" ? "live" : state.autoRefresh ? "polling" : "paused"; renderSourceHealth(); renderRealtimeSummary(); }
function clearStreamRetry() { if (state.streamRetryTimer) { clearTimeout(state.streamRetryTimer); state.streamRetryTimer = null; } }
function scheduleStreamRetry() { clearStreamRetry(); if (!state.autoRefresh || state.stream || typeof EventSource !== "function") return; const delay = Math.max(5000, Math.min(60_000, Number(state.streamRetryDelayMs) || 5000)); state.streamRetryTimer = setTimeout(() => { state.streamRetryTimer = null; if (state.autoRefresh && !state.stream) connectStream(); }, delay); state.streamRetryDelayMs = Math.min(60_000, delay * 2); }
function closeStream() { clearStreamRetry(); if (state.stream) { try { state.stream.close(); } catch { /* already closed */ } state.stream = null; } state.streamRetryDelayMs = 5000; }
function clearRefreshTimer() { if (state.timer) { clearTimeout(state.timer); state.timer = null; } }
function schedulePolling() { clearRefreshTimer(); if (!state.autoRefresh || state.stream) { state.nextRefreshAt = null; renderRealtimeState(); return; } const interval = Math.max(15000, Number(state.refreshIntervalMs) || REFRESH_INTERVAL_MS); state.refreshIntervalMs = interval; state.nextRefreshAt = Date.now() + interval; state.streamState = "polling"; state.timer = setTimeout(() => refresh("poll"), interval); renderRealtimeState(); scheduleStreamRetry(); }
function connectStream() { if (!state.autoRefresh || state.stream) return; if (typeof EventSource !== "function") { schedulePolling(); return; } state.streamState = "connecting"; renderRealtimeState(); let opened = false; let source; try { source = new EventSource(STREAM_URL); } catch { state.lastError = "实时流不可用，已切换轮询"; schedulePolling(); return; } state.stream = source; source.onopen = () => { opened = true; state.streamState = "live"; state.nextRefreshAt = null; state.lastError = ""; renderRealtimeState(); }; const handleStreamEvent = (event) => { try { const payload = JSON.parse(event.data || "{}"); const hasXml = Array.isArray(payload.sources) && payload.sources.some((entry) => entry && entry.xml); const serverInterval = Number(payload?.refreshIntervalMs); if (serverInterval >= 15000) state.refreshIntervalMs = serverInterval; const nextRefresh = payload?.nextRefreshAt ? new Date(payload.nextRefreshAt).getTime() : NaN; if (Number.isFinite(nextRefresh)) state.nextRefreshAt = nextRefresh; if (!hasXml) { if (Array.isArray(payload.sources)) { state.sourceStatuses = payload.sources; state.sourceErrorCount = state.sourceStatuses.filter((entry) => entry.status === "error").length; } if (payload?.refreshedAt) state.lastSyncAt = payload.refreshedAt; state.streamState = "live"; state.lastError = ""; render({ preserveViewport: true }); if (Array.isArray(payload.changedSources) && payload.changedSources.length) refresh("stream"); return; } applyFeedPayload(payload, "stream"); render({ preserveViewport: true }); } catch { /* ignore malformed stream events */ } }; source.addEventListener("snapshot", handleStreamEvent); source.addEventListener("update", handleStreamEvent); source.onmessage = handleStreamEvent; source.onerror = () => { source.close(); if (state.stream === source) state.stream = null; state.streamState = "stale"; state.lastError = opened ? "实时流已断开，正在切换轮询" : "实时流不可用，已切换轮询"; schedulePolling(); }; }
async function refresh(reason = "manual") { if (state.refreshInFlight) { if (reason === "stream") state.pendingRefresh = true; return; } if (reason === "stream") state.pendingRefresh = false; state.refreshInFlight = true; clearRefreshTimer(); $("refresh-btn").disabled = true; state.streamState = state.stream ? "live" : "syncing"; renderRealtimeState(); try { const payload = await fetchFeedPayload(); applyFeedPayload(payload, "poll"); if (reason === "manual") showToast(state.hasLiveData ? "公开源已更新" : "暂时使用演示数据"); } catch (error) { state.lastError = error?.message || "公开源连接失败"; if (!state.hasLiveData) { state.items = DEMO_ITEMS.map((item) => enrich(item)); state.live = false; } else { state.live = true; } state.streamState = state.hasLiveData ? "stale" : "error"; if (reason === "manual") showToast(state.hasLiveData ? "连接暂时中断，保留上次数据" : "公开源连接失败，保留演示数据"); } finally { state.refreshInFlight = false; $("refresh-btn").disabled = false; const queued = state.pendingRefresh && state.autoRefresh; state.pendingRefresh = false; if (state.autoRefresh && !state.stream) schedulePolling(); render({ preserveViewport: true }); if (queued) setTimeout(() => refresh("stream"), 0); } }
function setAutoRefresh(enabled, persist = true) { state.autoRefresh = Boolean(enabled); if (persist) saveStored("yihot-auto-refresh", state.autoRefresh); clearRefreshTimer(); if (!state.autoRefresh) { state.pendingRefresh = false; closeStream(); state.nextRefreshAt = null; state.streamState = "paused"; } else if (!state.stream) { state.streamState = "connecting"; connectStream(); if (!state.stream) schedulePolling(); } syncAutoControls(); renderRealtimeState(); }
 function syncAutoControls() { $("poll-toggle").checked = state.autoRefresh; $("auto-refresh-btn").textContent = state.autoRefresh ? "暂停自动刷新" : "恢复自动刷新"; $("auto-refresh-btn").setAttribute("aria-pressed", String(!state.autoRefresh)); $("poll-label").textContent = state.autoRefresh ? `${formatInterval(state.refreshIntervalMs)}自动刷新` : "自动刷新已暂停"; }
function startRealtime() { syncAutoControls(); state.countdownTimer = setInterval(updateCountdown, 1000); if (state.autoRefresh) { refresh("initial"); connectStream(); } else { state.streamState = "paused"; renderRealtimeState(); } }
  function downloadJson() { const payload = { exportedAt: new Date().toISOString(), product: "YIHOT", mode: state.live ? "allowlist-public-source" : "demo", filters: { view: state.currentView, topic: state.filter, source: state.sourceFilter, range: state.range, actionOnly: state.actionOnly, query: state.query }, items: filteredItems().map((item) => ({ ...item, citation: safeHref(item.url) })) }; const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" }); const href = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = href; link.download = "yihot-export.json"; link.click(); setTimeout(() => URL.revokeObjectURL(href), 0); showToast("已导出当前筛选结果"); }
function showToast(message) { const toast = $("toast"); toast.textContent = message; toast.hidden = false; clearTimeout(showToast.timer); showToast.timer = setTimeout(() => { toast.hidden = true; }, 2200); }
  document.addEventListener("click", (event) => { const viewButton = event.target.closest("[data-view], [data-view-link]"); if (viewButton) { event.preventDefault(); setView(viewButton.dataset.view || viewButton.dataset.viewLink); return; } const filter = event.target.closest("[data-filter]"); if (filter) { state.filter = filter.dataset.filter; document.querySelectorAll(".filter-tab").forEach((button) => { const active = button === filter; button.classList.toggle("active", active); button.setAttribute("aria-selected", String(active)); }); render(); return; } const queueButton = event.target.closest("[data-queue]"); if (queueButton) { const id = queueButton.dataset.queue; const item = state.items.find((entry) => entry.id === id) || state.queue.find((entry) => entry.id === id); if (!item) return; const wasQueued = isQueued(id); state.queue = wasQueued ? state.queue.filter((entry) => entry.id !== id) : [...state.queue, item]; saveStored("yihot-queue", state.queue); render(); showToast(wasQueued ? "已移出复核队列" : "已加入复核队列"); return; } const starButton = event.target.closest("[data-star]"); if (starButton) { const id = starButton.dataset.star; const wasStarred = isStarred(id); state.starred = wasStarred ? state.starred.filter((value) => value !== id) : [...state.starred, id]; saveStored("yihot-starred", state.starred); render(); showToast(wasStarred ? "已取消收藏" : "已收藏"); return; } const daily = event.target.closest("[data-daily-date]"); if (daily) { state.dailyDate = daily.dataset.dailyDate; renderDaily(filteredItems()); return; } });
$("search-form").addEventListener("submit", (event) => { event.preventDefault(); state.query = $("search-input").value.trim(); render(); });
$("search-input").addEventListener("input", (event) => { state.query = event.target.value.trim(); render(); });
$("range-select").addEventListener("change", (event) => { state.range = event.target.value; render(); });
$("source-select").addEventListener("change", (event) => { state.sourceFilter = event.target.value; render(); });
$("action-only").addEventListener("change", (event) => { state.actionOnly = event.target.checked; render(); });
$("refresh-btn").addEventListener("click", refresh);
$("export-btn").addEventListener("click", downloadJson);
  $("clear-queue").addEventListener("click", () => { if (!state.queue.length) return; state.queue = []; saveStored("yihot-queue", state.queue); render(); showToast("已清空复核队列"); });
$("poll-toggle").addEventListener("change", (event) => { setAutoRefresh(event.target.checked); showToast(event.target.checked ? "已恢复自动刷新" : "自动刷新已暂停"); });
$("auto-refresh-btn").addEventListener("click", () => { setAutoRefresh(!state.autoRefresh); showToast(state.autoRefresh ? "已恢复自动刷新" : "自动刷新已暂停"); });
$("show-new-items").addEventListener("click", () => { state.pendingNewIds = []; renderNewItemsBanner(); render(); document.querySelector(".primary")?.scrollIntoView({ behavior: "smooth", block: "start" }); showToast("已显示最新信息，当前筛选保持不变"); });
$("dismiss-new-items").addEventListener("click", () => { state.pendingNewIds = []; renderNewItemsBanner(); });
  $("theme-toggle").addEventListener("click", () => { const dark = document.documentElement.dataset.theme === "dark"; document.documentElement.dataset.theme = dark ? "light" : "dark"; saveStored("yihot-theme", dark ? "light" : "dark"); });
$("menu-toggle").addEventListener("click", () => { const sidebar = $("sidebar"); const open = sidebar.classList.toggle("open"); $("menu-toggle").setAttribute("aria-expanded", String(open)); });
  const savedTheme = loadStoredCompat("yihot-theme", "civic-radar-theme", null); if (savedTheme === "dark" || savedTheme === "light") document.documentElement.dataset.theme = savedTheme;
state.items = state.items.map((item) => enrich(item));
state.sourceStatuses = [...ALLOWED_SOURCE_IDS].map((id) => ({ id, name: id, status: "pending" }));
setView("featured");
startRealtime();
